### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [IVCenter/ParallelRaytracing#1]
Hello , under what license is this project released under ? Thank-you.

**Comment by rexwest** [comment]
Hi suprafun,

I added an MIT license to the project.  Any source files with a separate license or that cite code under a separate license will be under those licenses instead.

This was a project I had worked on during my undergrad and is mostly no longer in active development.  If you're looking for a physically-based rendering engine that's open source and is in active development you might check out PBRT or Mitsuba.
